# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - log_dir: default.yaml
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog


work_dir: ${hydra:runtime.cwd}

# Configuration options for creating HDF5 datasets
create_h5dataset:
  # Path to the CSV file containing enzyme information
  csv_file: ${work_dir}/data/csv/full_enzyme_set.csv

  # Root directory containing PDB files
  pdb_root: "/p/scratch/vsk33/vanderweg/topec_data/all_structures"

  # Root directory where HDF5 files will be stored
  h5_root: "/p/project/vsk33/vanderweg/TopEC/data/h5"

  # Name of the HDF5 file to be created
  h5_name: "all_enzymes.h5"

  # Number of CPUs for parallel processing
  n_cpus: 64  # Adjust this number according to your system configuration

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

