# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: enzyme.yaml # choose the datamodule for evaluation
  - model: schnet.yaml
  - callbacks: null
  - logger: null
  - trainer: test.yaml
  - log_dir: evaluation.yaml

  - experiment: schnet_TopM_BM.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: /p/project/vsk33/vanderweg/enzyme_prediction_gold_test/data/processed/all_enzymes/
csv_dir: ${original_work_dir}/data/split_csv/

print_config: True

ignore_warnings: True

seed: 12345

name: "default"

# passing checkpoint path is necessary
ckpt_path: /p/project/vsk33/vanderweg/enzyme-function-prediction/logs/experiments/runs/schnet_AF2_FOLD/2022-09-08_10-27-34/checkpoints/val_acc.ckpt

pycm_report_dir: /p/project/vsk33/vanderweg/enzyme-function-prediction/logs/evaluations/runs/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}/